version: '3.8'

services:
  # База данных
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=online_customer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  # Админ панель
  admin:
    build:
      context: ./admin_service
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/online_customer
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-this-in-production}
    depends_on:
      - db
    volumes:
      - ./admin_service/admin/static:/app/admin/static
      - ./admin_service/admin/templates:/app/admin/templates
    restart: unless-stopped
    networks:
      - app-network

  # Telegram бот
  bot:
    build:
      context: ./bot_service
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/online_customer
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
