"""add_phone_to_orders

Revision ID: 7854e42178cc
Revises: 89a358d6782e
Create Date: 2025-09-03 18:24:35.669645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7854e42178cc'
down_revision: Union[str, None] = '89a358d6782e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone')
    # ### end Alembic commands ###
